
2021-02-12T16:20:03Z systemd[1]: Started Service for snap application kubelet.daemon.
2021-02-12T16:20:03Z kubelet.daemon[43543]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
2021-02-12T16:20:03Z kubelet.daemon[43543]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
2021-02-12T16:20:03Z kubelet.daemon[43543]: I0212 13:20:03.230299   43543 server.go:416] Version: v1.20.2
2021-02-12T16:20:03Z kubelet.daemon[43543]: I0212 13:20:03.230587   43543 server.go:837] Client rotation is on, will bootstrap in background
2021-02-12T16:20:03Z kubelet.daemon[43543]: I0212 13:20:03.232854   43543 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
2021-02-12T16:20:03Z kubelet.daemon[43543]: I0212 13:20:03.252452   43543 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/pki/ca.crt
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.282766   43543 server.go:645] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283523   43543 container_manager_linux.go:274] container manager verified user specified cgroup-root exists: []
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283535   43543 container_manager_linux.go:279] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283594   43543 topology_manager.go:120] [topologymanager] Creating topology manager with none policy per container scope
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283601   43543 container_manager_linux.go:310] [topologymanager] Initializing Topology Manager with none policy and container-level scope
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283605   43543 container_manager_linux.go:315] Creating device plugin manager: true
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283660   43543 remote_runtime.go:62] parsed scheme: ""
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283665   43543 remote_runtime.go:62] scheme "" not registered, fallback to default scheme
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283685   43543 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/run/crio/crio.sock  <nil> 0 <nil>}] <nil> <nil>}
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283691   43543 clientconn.go:948] ClientConn switching balancer to "pick_first"
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283721   43543 remote_image.go:50] parsed scheme: ""
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283725   43543 remote_image.go:50] scheme "" not registered, fallback to default scheme
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283732   43543 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/run/crio/crio.sock  <nil> 0 <nil>}] <nil> <nil>}
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283735   43543 clientconn.go:948] ClientConn switching balancer to "pick_first"
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283795   43543 kubelet.go:262] Adding pod path: /etc/kubernetes/manifests
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.283811   43543 kubelet.go:273] Watching apiserver
2021-02-12T16:20:08Z kubelet.daemon[43543]: E0212 13:20:08.300639   43543 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dcgroovy&limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:08Z kubelet.daemon[43543]: E0212 13:20:08.300784   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:08Z kubelet.daemon[43543]: E0212 13:20:08.300835   43543 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/kubelet.go:438: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcgroovy&limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:08Z kubelet.daemon[43543]: I0212 13:20:08.305454   43543 kuberuntime_manager.go:216] Container runtime cri-o initialized, version: 1.20.0, apiVersion: v1alpha1
2021-02-12T16:20:09Z kubelet.daemon[43543]: E0212 13:20:09.424885   43543 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/kubelet.go:438: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcgroovy&limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:09Z kubelet.daemon[43543]: E0212 13:20:09.517383   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:09Z kubelet.daemon[43543]: E0212 13:20:09.615687   43543 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dcgroovy&limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:11Z kubelet.daemon[43543]: E0212 13:20:11.527873   43543 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dcgroovy&limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:12Z kubelet.daemon[43543]: E0212 13:20:12.260708   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:12Z kubelet.daemon[43543]: E0212 13:20:12.297797   43543 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/kubelet.go:438: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcgroovy&limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.554265   43543 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
2021-02-12T16:20:14Z kubelet.daemon[43543]:     For verbose messaging see aws.Config.CredentialsChainVerboseErrors
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.557299   43543 server.go:1176] Started kubelet
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.557356   43543 server.go:148] Starting to listen on 0.0.0.0:10250
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.558960   43543 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b241704dc", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa11118dc, ext:11388354660, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa11118dc, ext:11388354660, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Post "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/namespaces/default/events": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused'(may retry after sleeping)
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.564031   43543 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.579695   43543 volume_manager.go:271] Starting Kubelet Volume Manager
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.579971   43543 desired_state_of_world_populator.go:142] Desired state populator starts to run
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.580326   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://[IPV6-PUBLIC-SLAAC]:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.580337   43543 server.go:410] Adding debug handlers to kubelet server.
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.580364   43543 controller.go:144] failed to ensure lease exists, will retry in 200ms, error: Get "https://[IPV6-PUBLIC-SLAAC]:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/cgroovy?timeout=10s": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.581686   43543 cri_stats_provider.go:376] Failed to get the info of the filesystem with mountpoint "/etc/containers/storage/overlay-images": unable to find data in memory cache.
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.581698   43543 kubelet.go:1274] Image garbage collection failed once. Stats initialization may not have completed yet: invalid capacity 0 on image filesystem
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.604998   43543 kubelet_network_linux.go:56] Initialized IPv4 iptables rules.
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.670663   43543 kubelet_network_linux.go:56] Initialized IPv6 iptables rules.
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.670694   43543 status_manager.go:158] Starting to sync pod status with apiserver
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.670706   43543 kubelet.go:1802] Starting kubelet main sync loop.
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.670769   43543 kubelet.go:1826] skipping pod synchronization - [container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.671415   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://[IPV6-PUBLIC-SLAAC]:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.679826   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.691235   43543 kubelet_node_status.go:71] Attempting to register node cgroovy
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.691641   43543 kubelet_node_status.go:93] Unable to register node "cgroovy" with API server: Post "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/nodes": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.728395   43543 cpu_manager.go:193] [cpumanager] starting with none policy
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.728406   43543 cpu_manager.go:194] [cpumanager] reconciling every 10s
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.730887   43543 state_mem.go:36] [cpumanager] initializing new in-memory state store
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.732867   43543 policy_none.go:43] [cpumanager] none policy: Start
2021-02-12T16:20:14Z kubelet.daemon[43543]: W0212 13:20:14.733478   43543 manager.go:594] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.733732   43543 plugin_manager.go:114] Starting Kubelet Plugin Manager
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.734345   43543 eviction_manager.go:260] eviction manager: failed to get summary stats: failed to get node info: node "cgroovy" not found
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.770881   43543 topology_manager.go:187] [topologymanager] Topology Admit Handler
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.775098   43543 topology_manager.go:187] [topologymanager] Topology Admit Handler
2021-02-12T16:20:14Z kubelet.daemon[43543]: W0212 13:20:14.779525   43543 status_manager.go:550] Failed to get status for pod "etcd-cgroovy_kube-system(e2f02e42557bf3e29ddd30e222958cba)": Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/namespaces/kube-system/pods/etcd-cgroovy": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.779920   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.780577   43543 controller.go:144] failed to ensure lease exists, will retry in 400ms, error: Get "https://[IPV6-PUBLIC-SLAAC]:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/cgroovy?timeout=10s": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.781394   43543 topology_manager.go:187] [topologymanager] Topology Admit Handler
2021-02-12T16:20:14Z kubelet.daemon[43543]: W0212 13:20:14.792766   43543 status_manager.go:550] Failed to get status for pod "kube-apiserver-cgroovy_kube-system(069f8f2d4aedab206f739e4e26fd9491)": Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/namespaces/kube-system/pods/kube-apiserver-cgroovy": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.792868   43543 topology_manager.go:187] [topologymanager] Topology Admit Handler
2021-02-12T16:20:14Z kubelet.daemon[43543]: W0212 13:20:14.797285   43543 status_manager.go:550] Failed to get status for pod "kube-controller-manager-cgroovy_kube-system(f046e2360d84028b22e0cfd40f66d526)": Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/namespaces/kube-system/pods/kube-controller-manager-cgroovy": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: W0212 13:20:14.801603   43543 status_manager.go:550] Failed to get status for pod "kube-scheduler-cgroovy_kube-system(d33e3ee91628b4b34795c7c68c786727)": Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/namespaces/kube-system/pods/kube-scheduler-cgroovy": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.880045   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880274   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "etc-ca-certificates" (UniqueName: "kubernetes.io/host-path/f046e2360d84028b22e0cfd40f66d526-etc-ca-certificates") pod "kube-controller-manager-cgroovy" (UID: "f046e2360d84028b22e0cfd40f66d526")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880292   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "etcd-certs" (UniqueName: "kubernetes.io/host-path/e2f02e42557bf3e29ddd30e222958cba-etcd-certs") pod "etcd-cgroovy" (UID: "e2f02e42557bf3e29ddd30e222958cba")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880303   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "ca-certs" (UniqueName: "kubernetes.io/host-path/f046e2360d84028b22e0cfd40f66d526-ca-certs") pod "kube-controller-manager-cgroovy" (UID: "f046e2360d84028b22e0cfd40f66d526")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880313   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "flexvolume-dir" (UniqueName: "kubernetes.io/host-path/f046e2360d84028b22e0cfd40f66d526-flexvolume-dir") pod "kube-controller-manager-cgroovy" (UID: "f046e2360d84028b22e0cfd40f66d526")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880323   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "k8s-certs" (UniqueName: "kubernetes.io/host-path/069f8f2d4aedab206f739e4e26fd9491-k8s-certs") pod "kube-apiserver-cgroovy" (UID: "069f8f2d4aedab206f739e4e26fd9491")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880333   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "etc-ca-certificates" (UniqueName: "kubernetes.io/host-path/069f8f2d4aedab206f739e4e26fd9491-etc-ca-certificates") pod "kube-apiserver-cgroovy" (UID: "069f8f2d4aedab206f739e4e26fd9491")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880343   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "k8s-certs" (UniqueName: "kubernetes.io/host-path/f046e2360d84028b22e0cfd40f66d526-k8s-certs") pod "kube-controller-manager-cgroovy" (UID: "f046e2360d84028b22e0cfd40f66d526")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880354   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "usr-local-share-ca-certificates" (UniqueName: "kubernetes.io/host-path/f046e2360d84028b22e0cfd40f66d526-usr-local-share-ca-certificates") pod "kube-controller-manager-cgroovy" (UID: "f046e2360d84028b22e0cfd40f66d526")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880366   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "usr-share-ca-certificates" (UniqueName: "kubernetes.io/host-path/f046e2360d84028b22e0cfd40f66d526-usr-share-ca-certificates") pod "kube-controller-manager-cgroovy" (UID: "f046e2360d84028b22e0cfd40f66d526")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880375   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "ca-certs" (UniqueName: "kubernetes.io/host-path/069f8f2d4aedab206f739e4e26fd9491-ca-certs") pod "kube-apiserver-cgroovy" (UID: "069f8f2d4aedab206f739e4e26fd9491")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880386   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "usr-local-share-ca-certificates" (UniqueName: "kubernetes.io/host-path/069f8f2d4aedab206f739e4e26fd9491-usr-local-share-ca-certificates") pod "kube-apiserver-cgroovy" (UID: "069f8f2d4aedab206f739e4e26fd9491")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880396   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "usr-share-ca-certificates" (UniqueName: "kubernetes.io/host-path/069f8f2d4aedab206f739e4e26fd9491-usr-share-ca-certificates") pod "kube-apiserver-cgroovy" (UID: "069f8f2d4aedab206f739e4e26fd9491")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880405   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "kubeconfig" (UniqueName: "kubernetes.io/host-path/f046e2360d84028b22e0cfd40f66d526-kubeconfig") pod "kube-controller-manager-cgroovy" (UID: "f046e2360d84028b22e0cfd40f66d526")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880415   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "kubeconfig" (UniqueName: "kubernetes.io/host-path/d33e3ee91628b4b34795c7c68c786727-kubeconfig") pod "kube-scheduler-cgroovy" (UID: "d33e3ee91628b4b34795c7c68c786727")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.880425   43543 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "etcd-data" (UniqueName: "kubernetes.io/host-path/e2f02e42557bf3e29ddd30e222958cba-etcd-data") pod "etcd-cgroovy" (UID: "e2f02e42557bf3e29ddd30e222958cba")
2021-02-12T16:20:14Z kubelet.daemon[43543]: I0212 13:20:14.895891   43543 kubelet_node_status.go:71] Attempting to register node cgroovy
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.896091   43543 kubelet_node_status.go:93] Unable to register node "cgroovy" with API server: Post "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/nodes": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:14Z kubelet.daemon[43543]: E0212 13:20:14.980188   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.080284   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.180574   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.189306   43543 controller.go:144] failed to ensure lease exists, will retry in 800ms, error: Get "https://[IPV6-PUBLIC-SLAAC]:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/cgroovy?timeout=10s": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.280705   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:15Z kubelet.daemon[43543]: I0212 13:20:15.340925   43543 kubelet_node_status.go:71] Attempting to register node cgroovy
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.341191   43543 kubelet_node_status.go:93] Unable to register node "cgroovy" with API server: Post "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/nodes": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.380804   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.469968   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://[IPV6-PUBLIC-SLAAC]:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp [IPV6-PUBLIC-SLAAC]:6443: connect: connection refused
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.481373   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.583228   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.683309   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.783396   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.883492   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:15Z kubelet.daemon[43543]: E0212 13:20:15.983587   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:16Z kubelet.daemon[43543]: E0212 13:20:16.083680   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:16Z kubelet.daemon[43543]: I0212 13:20:16.162549   43543 kubelet_node_status.go:71] Attempting to register node cgroovy
2021-02-12T16:20:16Z kubelet.daemon[43543]: E0212 13:20:16.183782   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:16Z kubelet.daemon[43543]: E0212 13:20:16.283878   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:16Z kubelet.daemon[43543]: E0212 13:20:16.383971   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:16Z kubelet.daemon[43543]: E0212 13:20:16.484081   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:16Z kubelet.daemon[43543]: E0212 13:20:16.584202   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:16Z kubelet.daemon[43543]: E0212 13:20:16.684289   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:16Z kubelet.daemon[43543]: E0212 13:20:16.784392   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:16Z kubelet.daemon[43543]: E0212 13:20:16.884530   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:16Z kubelet.daemon[43543]: E0212 13:20:16.984682   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:17Z kubelet.daemon[43543]: E0212 13:20:17.084790   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:17Z kubelet.daemon[43543]: E0212 13:20:17.184916   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:17Z kubelet.daemon[43543]: E0212 13:20:17.285020   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:17Z kubelet.daemon[43543]: E0212 13:20:17.385170   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:17Z kubelet.daemon[43543]: E0212 13:20:17.485306   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:17Z kubelet.daemon[43543]: E0212 13:20:17.585412   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:17Z kubelet.daemon[43543]: E0212 13:20:17.685524   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:17Z kubelet.daemon[43543]: E0212 13:20:17.785647   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:17Z kubelet.daemon[43543]: E0212 13:20:17.885782   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:17Z kubelet.daemon[43543]: E0212 13:20:17.985842   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.085951   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.186041   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.286967   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.387092   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.494011   43543 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/kubelet.go:438: Failed to watch *v1.Node: failed to list *v1.Node: Unauthorized
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.494127   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Unauthorized
2021-02-12T16:20:18Z kubelet.daemon[43543]: W0212 13:20:18.494155   43543 status_manager.go:550] Failed to get status for pod "kube-controller-manager-cgroovy_kube-system(f046e2360d84028b22e0cfd40f66d526)": Unauthorized
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.494254   43543 kubelet_node_status.go:93] Unable to register node "cgroovy" with API server: Unauthorized
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.494281   43543 controller.go:144] failed to ensure lease exists, will retry in 1.6s, error: Unauthorized
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.494319   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Unauthorized
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.494336   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.494367   43543 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to watch *v1.Pod: failed to list *v1.Pod: Unauthorized
2021-02-12T16:20:18Z kubelet.daemon[43543]: W0212 13:20:18.501547   43543 status_manager.go:550] Failed to get status for pod "etcd-cgroovy_kube-system(e2f02e42557bf3e29ddd30e222958cba)": Unauthorized
2021-02-12T16:20:18Z kubelet.daemon[43543]: W0212 13:20:18.504439   43543 status_manager.go:550] Failed to get status for pod "kube-apiserver-cgroovy_kube-system(069f8f2d4aedab206f739e4e26fd9491)": Unauthorized
2021-02-12T16:20:18Z kubelet.daemon[43543]: W0212 13:20:18.506255   43543 status_manager.go:550] Failed to get status for pod "kube-scheduler-cgroovy_kube-system(d33e3ee91628b4b34795c7c68c786727)": Unauthorized
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.594437   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.694604   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.794822   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.894952   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:18Z kubelet.daemon[43543]: E0212 13:20:18.995086   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:19Z kubelet.daemon[43543]: E0212 13:20:19.095222   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:19Z kubelet.daemon[43543]: E0212 13:20:19.195291   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:19Z kubelet.daemon[43543]: E0212 13:20:19.295413   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:19Z kubelet.daemon[43543]: E0212 13:20:19.395541   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:19Z kubelet.daemon[43543]: E0212 13:20:19.495652   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:19Z kubelet.daemon[43543]: E0212 13:20:19.595762   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:19Z kubelet.daemon[43543]: E0212 13:20:19.695868   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:19Z kubelet.daemon[43543]: E0212 13:20:19.795964   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:19Z kubelet.daemon[43543]: E0212 13:20:19.896203   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:19Z kubelet.daemon[43543]: E0212 13:20:19.996317   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.095011   43543 controller.go:144] failed to ensure lease exists, will retry in 3.2s, error: Unauthorized
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.096406   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:20Z kubelet.daemon[43543]: I0212 13:20:20.098875   43543 kubelet_node_status.go:71] Attempting to register node cgroovy
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.099406   43543 kubelet_node_status.go:93] Unable to register node "cgroovy" with API server: Unauthorized
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.196628   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.296731   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.397183   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.497354   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.597481   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.697637   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.797793   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.898014   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:20Z kubelet.daemon[43543]: E0212 13:20:20.998352   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.098603   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.198762   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.298819   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.399071   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.499294   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.599412   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.632241   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Unauthorized
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.637919   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Unauthorized
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.699625   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.799751   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:21Z kubelet.daemon[43543]: E0212 13:20:21.899975   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:22Z kubelet.daemon[43543]: E0212 13:20:22.000100   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:22Z kubelet.daemon[43543]: E0212 13:20:22.100538   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:22Z kubelet.daemon[43543]: E0212 13:20:22.200667   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:22Z kubelet.daemon[43543]: E0212 13:20:22.300792   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:22Z kubelet.daemon[43543]: E0212 13:20:22.400910   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:22Z kubelet.daemon[43543]: E0212 13:20:22.501016   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:22Z kubelet.daemon[43543]: E0212 13:20:22.601122   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:22Z kubelet.daemon[43543]: E0212 13:20:22.701274   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:22Z kubelet.daemon[43543]: E0212 13:20:22.801491   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:22Z kubelet.daemon[43543]: E0212 13:20:22.901614   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.001712   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.102018   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.202205   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.295638   43543 controller.go:144] failed to ensure lease exists, will retry in 6.4s, error: Unauthorized
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.302325   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:23Z kubelet.daemon[43543]: I0212 13:20:23.303625   43543 kubelet_node_status.go:71] Attempting to register node cgroovy
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.304302   43543 kubelet_node_status.go:93] Unable to register node "cgroovy" with API server: Unauthorized
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.402556   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.502769   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.602900   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.703124   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.803343   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:23Z kubelet.daemon[43543]: E0212 13:20:23.903552   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.003700   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.103843   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.203960   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.304187   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.393972   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b241704dc", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa11118dc, ext:11388354660, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa11118dc, ext:11388354660, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.394488   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b25b1dd23", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"InvalidDiskCapacity", Message:"invalid capacity 0 on image filesystem", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa2abf123, ext:11415279782, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa2abf123, ext:11415279782, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.394875   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c389bfe", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node cgroovy status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932affe, ext:11524773763, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932affe, ext:11524773763, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.395273   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38b487", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node cgroovy status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932c887, ext:11524780042, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932c887, ext:11524780042, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.395639   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38beff", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node cgroovy status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932d2ff, ext:11524782721, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932d2ff, ext:11524782721, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.396214   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c389bfe", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node cgroovy status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932affe, ext:11524773763, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fab659ee2, ext:11561666151, loc:(*time.Location)(0x72ea080)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.396683   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38b487", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node cgroovy status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932c887, ext:11524780042, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fab65bd1e, ext:11561673891, loc:(*time.Location)(0x72ea080)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.397105   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38beff", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node cgroovy status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932d2ff, ext:11524782721, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fab65c6ce, ext:11561676371, loc:(*time.Location)(0x72ea080)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.397565   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2ec286d4", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeAllocatableEnforced", Message:"Updated Node Allocatable limit across pods", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fabbc9ad4, ext:11567366744, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fabbc9ad4, ext:11567366744, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.397964   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c389bfe", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node cgroovy status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932affe, ext:11524773763, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fae322514, ext:11608624281, loc:(*time.Location)(0x72ea080)}}, Count:3, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.404401   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.504604   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.591693   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38beff", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node cgroovy status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932d2ff, ext:11524782721, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fae3248a0, ext:11608633382, loc:(*time.Location)(0x72ea080)}}, Count:3, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.604835   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.704990   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.734497   43543 eviction_manager.go:260] eviction manager: failed to get summary stats: failed to get node info: node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.791717   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38b487", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node cgroovy status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932c887, ext:11524780042, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fae323f43, ext:11608630982, loc:(*time.Location)(0x72ea080)}}, Count:3, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.805079   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.905241   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:24Z kubelet.daemon[43543]: E0212 13:20:24.993764   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38b487", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node cgroovy status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932c887, ext:11524780042, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fae725427, ext:11612830635, loc:(*time.Location)(0x72ea080)}}, Count:4, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.005500   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.105556   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.191678   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c389bfe", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node cgroovy status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932affe, ext:11524773763, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fae723754, ext:11612823257, loc:(*time.Location)(0x72ea080)}}, Count:4, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.205656   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.305891   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.391743   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38beff", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node cgroovy status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932d2ff, ext:11524782721, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fae725c6a, ext:11612832748, loc:(*time.Location)(0x72ea080)}}, Count:4, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.406013   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.506250   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.591805   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c389bfe", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node cgroovy status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932affe, ext:11524773763, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fae78e1b8, ext:11613260096, loc:(*time.Location)(0x72ea080)}}, Count:5, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.606446   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.706594   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.791762   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38b487", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node cgroovy status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932c887, ext:11524780042, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fae78ed9e, ext:11613263138, loc:(*time.Location)(0x72ea080)}}, Count:5, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.807938   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.908070   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.958755   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Unauthorized
2021-02-12T16:20:25Z kubelet.daemon[43543]: E0212 13:20:25.991741   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38beff", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node cgroovy status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932d2ff, ext:11524782721, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fae794f10, ext:11613288083, loc:(*time.Location)(0x72ea080)}}, Count:5, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.008199   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.108342   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.191978   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c389bfe", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node cgroovy status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932affe, ext:11524773763, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88faf396383, ext:11625876230, loc:(*time.Location)(0x72ea080)}}, Count:6, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.208500   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.308710   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.391751   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38b487", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node cgroovy status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932c887, ext:11524780042, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88faf3972e7, ext:11625880172, loc:(*time.Location)(0x72ea080)}}, Count:6, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.408755   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.508962   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.591742   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38beff", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node cgroovy status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932d2ff, ext:11524782721, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88faf397c69, ext:11625882604, loc:(*time.Location)(0x72ea080)}}, Count:6, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.609179   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.709365   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.791814   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c389bfe", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node cgroovy status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932affe, ext:11524773763, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88faf41538f, ext:11626396434, loc:(*time.Location)(0x72ea080)}}, Count:7, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.809500   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.827521   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Unauthorized
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.909722   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:26Z kubelet.daemon[43543]: E0212 13:20:26.996226   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38b487", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node cgroovy status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932c887, ext:11524780042, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88faf415dd9, ext:11626399069, loc:(*time.Location)(0x72ea080)}}, Count:7, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.009875   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.110030   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:27Z kubelet.daemon[43543]: W0212 13:20:27.167932   43543 status_manager.go:550] Failed to get status for pod "kube-controller-manager-cgroovy_kube-system(f046e2360d84028b22e0cfd40f66d526)": Unauthorized
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.191888   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38beff", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node cgroovy status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932d2ff, ext:11524782721, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88faf41668b, ext:11626401295, loc:(*time.Location)(0x72ea080)}}, Count:7, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.210229   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.310466   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.391914   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cgroovy.16630c7b2c38b487", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cgroovy", UID:"cgroovy", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node cgroovy status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fa932c887, ext:11524780042, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88faf80df3b, ext:11630560961, loc:(*time.Location)(0x72ea080)}}, Count:8, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.410674   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.510831   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.591891   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"etcd-cgroovy.16630c7b5666afa2", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"etcd-cgroovy", UID:"e2f02e42557bf3e29ddd30e222958cba", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{etcd}"}, Reason:"Pulled", Message:"Container image \"k8s.gcr.io/etcd:3.4.13-0\" already present on machine", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fd7c5f9a2, ext:12232436518, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fd7c5f9a2, ext:12232436518, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.595410   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Unauthorized
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.610922   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.711073   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.791749   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-apiserver-cgroovy.16630c7b567e4d7a", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-apiserver-cgroovy", UID:"069f8f2d4aedab206f739e4e26fd9491", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-apiserver}"}, Reason:"Pulled", Message:"Container image \"k8s.gcr.io/kube-apiserver:v1.20.0\" already present on machine", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fd7dd977a, ext:12233984252, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fd7dd977a, ext:12233984252, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.811286   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.911419   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:27Z kubelet.daemon[43543]: E0212 13:20:27.997567   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-controller-manager-cgroovy.16630c7b58ace50f", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-controller-manager-cgroovy", UID:"f046e2360d84028b22e0cfd40f66d526", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-controller-manager}"}, Reason:"Pulled", Message:"Container image \"k8s.gcr.io/kube-controller-manager:v1.20.0\" already present on machine", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fda0c2f0f, ext:12270592146, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fda0c2f0f, ext:12270592146, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.011646   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.111692   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.191819   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-apiserver-cgroovy.16630c7b5d12c57d", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-apiserver-cgroovy", UID:"069f8f2d4aedab206f739e4e26fd9491", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-apiserver}"}, Reason:"Created", Message:"Created container kube-apiserver", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fde720f7d, ext:12344377600, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fde720f7d, ext:12344377600, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.211996   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.312290   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.391886   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"etcd-cgroovy.16630c7b5def5a87", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"etcd-cgroovy", UID:"e2f02e42557bf3e29ddd30e222958cba", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{etcd}"}, Reason:"Created", Message:"Created container etcd", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fdf4ea487, ext:12358833674, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fdf4ea487, ext:12358833674, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.412454   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.512593   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.591632   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-controller-manager-cgroovy.16630c7b5e2140d1", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-controller-manager-cgroovy", UID:"f046e2360d84028b22e0cfd40f66d526", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-controller-manager}"}, Reason:"Created", Message:"Created container kube-controller-manager", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fdf808ad1, ext:12362103892, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fdf808ad1, ext:12362103892, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.612693   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.712809   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.791730   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-scheduler-cgroovy.16630c7b5e59115b", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-scheduler-cgroovy", UID:"d33e3ee91628b4b34795c7c68c786727", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-scheduler}"}, Reason:"Pulled", Message:"Container image \"k8s.gcr.io/kube-scheduler:v1.20.0\" already present on machine", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fdfb85b5b, ext:12365761758, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fdfb85b5b, ext:12365761758, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.812877   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.913096   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:28Z kubelet.daemon[43543]: E0212 13:20:28.991734   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-apiserver-cgroovy.16630c7b6281b935", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-apiserver-cgroovy", UID:"069f8f2d4aedab206f739e4e26fd9491", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-apiserver}"}, Reason:"Started", Message:"Started container kube-apiserver", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fe3e10335, ext:12435535032, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fe3e10335, ext:12435535032, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.013263   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.113390   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.191740   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-controller-manager-cgroovy.16630c7b63f636a1", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-controller-manager-cgroovy", UID:"f046e2360d84028b22e0cfd40f66d526", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-controller-manager}"}, Reason:"Started", Message:"Started container kube-controller-manager", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fe55580a1, ext:12459946533, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fe55580a1, ext:12459946533, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.213521   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.313732   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.391805   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"etcd-cgroovy.16630c7b65409bc2", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"etcd-cgroovy", UID:"e2f02e42557bf3e29ddd30e222958cba", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{etcd}"}, Reason:"Started", Message:"Started container etcd", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fe69fe5c2, ext:12481599301, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fe69fe5c2, ext:12481599301, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.413908   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.514063   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.591646   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-scheduler-cgroovy.16630c7b6850a851", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-scheduler-cgroovy", UID:"d33e3ee91628b4b34795c7c68c786727", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-scheduler}"}, Reason:"Created", Message:"Created container kube-scheduler", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fe9aff251, ext:12532982742, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fe9aff251, ext:12532982742, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.614288   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.698738   43543 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Unauthorized
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.715003   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:29Z kubelet.daemon[43543]: I0212 13:20:29.725229   43543 kubelet_node_status.go:71] Attempting to register node cgroovy
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.728709   43543 kubelet_node_status.go:93] Unable to register node "cgroovy" with API server: Unauthorized
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.791794   43543 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-scheduler-cgroovy.16630c7b6ad5a154", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-scheduler-cgroovy", UID:"d33e3ee91628b4b34795c7c68c786727", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-scheduler}"}, Reason:"Started", Message:"Started container kube-scheduler", Source:v1.EventSource{Component:"kubelet", Host:"cgroovy"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fec34eb54, ext:12575251672, loc:(*time.Location)(0x72ea080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc001c88fec34eb54, ext:12575251672, loc:(*time.Location)(0x72ea080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Unauthorized' (will not retry!)
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.815942   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:29Z kubelet.daemon[43543]: W0212 13:20:29.885401   43543 status_manager.go:550] Failed to get status for pod "etcd-cgroovy_kube-system(e2f02e42557bf3e29ddd30e222958cba)": Unauthorized
2021-02-12T16:20:29Z kubelet.daemon[43543]: E0212 13:20:29.916070   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.016305   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.116533   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.137566   43543 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/kubelet.go:438: Failed to watch *v1.Node: failed to list *v1.Node: Unauthorized
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.216635   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.316723   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.416765   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.517184   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.617339   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.717460   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.723684   43543 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to watch *v1.Pod: failed to list *v1.Pod: Unauthorized
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.817679   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: E0212 13:20:30.917897   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:30Z kubelet.daemon[43543]: W0212 13:20:30.959872   43543 status_manager.go:550] Failed to get status for pod "kube-apiserver-cgroovy_kube-system(069f8f2d4aedab206f739e4e26fd9491)": Unauthorized
2021-02-12T16:20:31Z kubelet.daemon[43543]: E0212 13:20:31.018123   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:31Z kubelet.daemon[43543]: E0212 13:20:31.118285   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:31Z kubelet.daemon[43543]: E0212 13:20:31.218459   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:31Z kubelet.daemon[43543]: E0212 13:20:31.318651   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:31Z kubelet.daemon[43543]: W0212 13:20:31.337665   43543 status_manager.go:550] Failed to get status for pod "kube-apiserver-cgroovy_kube-system(069f8f2d4aedab206f739e4e26fd9491)": Unauthorized
2021-02-12T16:20:31Z kubelet.daemon[43543]: E0212 13:20:31.418776   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:31Z kubelet.daemon[43543]: E0212 13:20:31.518924   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:31Z kubelet.daemon[43543]: E0212 13:20:31.618965   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:31Z kubelet.daemon[43543]: E0212 13:20:31.719341   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:31Z kubelet.daemon[43543]: E0212 13:20:31.819492   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:31Z kubelet.daemon[43543]: E0212 13:20:31.919713   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: E0212 13:20:32.019949   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: E0212 13:20:32.120230   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: E0212 13:20:32.220340   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: E0212 13:20:32.320471   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: E0212 13:20:32.420678   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: E0212 13:20:32.520893   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: E0212 13:20:32.620993   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: E0212 13:20:32.721205   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: E0212 13:20:32.821251   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: E0212 13:20:32.921467   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:32Z kubelet.daemon[43543]: W0212 13:20:32.990996   43543 status_manager.go:550] Failed to get status for pod "kube-scheduler-cgroovy_kube-system(d33e3ee91628b4b34795c7c68c786727)": Unauthorized
2021-02-12T16:20:33Z kubelet.daemon[43543]: E0212 13:20:33.021609   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:33Z kubelet.daemon[43543]: E0212 13:20:33.121777   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:33Z kubelet.daemon[43543]: E0212 13:20:33.221903   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:33Z kubelet.daemon[43543]: E0212 13:20:33.322031   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:33Z kubelet.daemon[43543]: E0212 13:20:33.422249   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:33Z kubelet.daemon[43543]: E0212 13:20:33.522461   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:33Z kubelet.daemon[43543]: E0212 13:20:33.622683   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:33Z kubelet.daemon[43543]: E0212 13:20:33.722811   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:33Z kubelet.daemon[43543]: E0212 13:20:33.822944   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:33Z kubelet.daemon[43543]: E0212 13:20:33.923167   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.023232   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.123621   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.223755   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.323982   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.424214   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.524368   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.624517   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.724748   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.742440   43543 eviction_manager.go:260] eviction manager: failed to get summary stats: failed to get node info: node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.824974   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:34Z kubelet.daemon[43543]: E0212 13:20:34.925187   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:35Z kubelet.daemon[43543]: E0212 13:20:35.025425   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:35Z kubelet.daemon[43543]: E0212 13:20:35.125551   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:35Z kubelet.daemon[43543]: E0212 13:20:35.225742   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:35Z kubelet.daemon[43543]: E0212 13:20:35.326043   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:35Z kubelet.daemon[43543]: E0212 13:20:35.426211   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:35Z kubelet.daemon[43543]: E0212 13:20:35.526360   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:35Z kubelet.daemon[43543]: E0212 13:20:35.626587   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:35Z kubelet.daemon[43543]: E0212 13:20:35.726718   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:35Z kubelet.daemon[43543]: E0212 13:20:35.826934   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:35Z kubelet.daemon[43543]: E0212 13:20:35.927071   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.027302   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.127554   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.227706   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.327920   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.428136   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.528326   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.628360   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.699507   43543 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Unauthorized
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.728494   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:36Z kubelet.daemon[43543]: I0212 13:20:36.732951   43543 kubelet_node_status.go:71] Attempting to register node cgroovy
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.733555   43543 kubelet_node_status.go:93] Unable to register node "cgroovy" with API server: Unauthorized
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.828626   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:36Z kubelet.daemon[43543]: E0212 13:20:36.928901   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.029136   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.129220   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.229457   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.329560   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.429779   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.529908   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.630234   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.632815   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Unauthorized
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.730464   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.830591   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:37Z kubelet.daemon[43543]: E0212 13:20:37.930806   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:38Z kubelet.daemon[43543]: E0212 13:20:38.030927   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:38Z kubelet.daemon[43543]: E0212 13:20:38.131113   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:38Z kubelet.daemon[43543]: E0212 13:20:38.231206   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:38Z kubelet.daemon[43543]: E0212 13:20:38.331382   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:38Z kubelet.daemon[43543]: E0212 13:20:38.431503   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:38Z kubelet.daemon[43543]: E0212 13:20:38.531652   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:38Z kubelet.daemon[43543]: E0212 13:20:38.631811   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:38Z kubelet.daemon[43543]: E0212 13:20:38.732037   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:38Z kubelet.daemon[43543]: E0212 13:20:38.832254   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:38Z kubelet.daemon[43543]: E0212 13:20:38.932528   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:39Z kubelet.daemon[43543]: E0212 13:20:39.032978   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:39Z kubelet.daemon[43543]: E0212 13:20:39.133106   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:39Z kubelet.daemon[43543]: E0212 13:20:39.233214   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:39Z kubelet.daemon[43543]: E0212 13:20:39.333306   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:39Z kubelet.daemon[43543]: E0212 13:20:39.433486   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:39Z kubelet.daemon[43543]: E0212 13:20:39.533620   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:39Z kubelet.daemon[43543]: E0212 13:20:39.633828   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:39Z kubelet.daemon[43543]: E0212 13:20:39.733943   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:39Z kubelet.daemon[43543]: E0212 13:20:39.834049   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:39Z kubelet.daemon[43543]: E0212 13:20:39.934342   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.034501   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.134730   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.234848   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.334961   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.345614   43543 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Unauthorized
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.435088   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.535318   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.635546   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.735800   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.836034   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:40Z kubelet.daemon[43543]: E0212 13:20:40.936262   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:41Z kubelet.daemon[43543]: E0212 13:20:41.036417   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:41Z kubelet.daemon[43543]: E0212 13:20:41.136580   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:41Z kubelet.daemon[43543]: E0212 13:20:41.236762   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:41Z kubelet.daemon[43543]: E0212 13:20:41.336979   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:41Z kubelet.daemon[43543]: E0212 13:20:41.437132   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:41Z kubelet.daemon[43543]: E0212 13:20:41.537348   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:41Z kubelet.daemon[43543]: E0212 13:20:41.637483   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:41Z kubelet.daemon[43543]: E0212 13:20:41.737611   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:41Z kubelet.daemon[43543]: E0212 13:20:41.837796   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:41Z kubelet.daemon[43543]: E0212 13:20:41.937852   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:42Z kubelet.daemon[43543]: E0212 13:20:42.038081   43543 kubelet.go:2243] node "cgroovy" not found
2021-02-12T16:20:42Z kubelet.daemon[43543]: E0212 13:20:42.138208   43543 kubelet.go:2243] node "cgroovy" not found
